docs: Add code snippet as an example for a user doc
eclipse-esmf/esmf-sdk-py-aspect-model-loader pull request #10
Opened 2023-06-12 10:15 UTC by Hanna-Shalamitskaya-EPAM

RBS-5932

2023-06-13 06:13 UTC, ysrbo approved these changes

2023-06-14 08:55 UTC, atextor approved these changes

2023-06-14 08:56 UTC, atextor requested changes

2023-06-14 08:56 UTC, atextor commented on documentation/python-sdk-guide/modules/ROOT/pages/index.adoc
> +hthttps://github.com/eclipse-esmf/esmf-aspect-model-editor/blob/main/core/apps/ame/src/assets/aspect-models/org.eclipse.examples.movement/1.0.0/Movement.ttl
* Typo at the beginning of the line (hthttp)
* I'd rather write "The examples below will be using the ..."

2023-06-20 08:39 UTC, atextor approved these changes

2023-06-20 08:42 UTC, merged