Small refactor of data types
eclipse-esmf/esmf-sdk-py-aspect-model-loader pull request #12
Opened 2023-07-10 08:56 UTC by Hanna-Shalamitskaya-EPAM

2023-07-10 12:01 UTC, atextor requested changes

2023-07-11 06:11 UTC, Hanna-Shalamitskaya-EPAM commented on core/esmf-aspect-meta-model-python/esmf_aspect_meta_model_python/base/cache_strategy.py
> +            Base | None: Element or undefined if it does not exists.
You are right. It is a grammatical mistake

2023-07-11 06:43 UTC, Hanna-Shalamitskaya-EPAM commented on core/esmf-aspect-meta-model-python/esmf_aspect_meta_model_python/base/contraints/regular_expression_constraint.py
> +    Restricts a string value to a regular expression as defined by XQuery 1.0 and XPath 2.0 Functions and Operators [xpath-functions]."""
Fixed

2023-07-11 06:44 UTC, Hanna-Shalamitskaya-EPAM commented on core/esmf-aspect-meta-model-python/esmf_aspect_meta_model_python/base/cache_strategy.py
> +            Base | None: Element or undefined if it does not exists.
Fixed

2023-07-12 10:47 UTC, atextor approved these changes

2023-07-12 10:48 UTC, merged