Support SAMM 2.1.0 version
eclipse-esmf/esmf-sdk-py-aspect-model-loader pull request #16
Opened 2023-10-06 11:45 UTC by Hanna-Shalamitskaya-EPAM

2023-10-09 08:56 UTC, atextor requested changes

2023-10-09 08:56 UTC, atextor commented on core/esmf-aspect-meta-model-python/tests/integration/test_subclasses.py
> +        SortedSet,
Is this duplicated line intentional?

2023-10-09 09:12 UTC, Hanna-Shalamitskaya-EPAM commented on core/esmf-aspect-meta-model-python/tests/integration/test_subclasses.py
> +        SortedSet,
Fixed

2023-10-10 08:37 UTC, atextor approved these changes

2023-10-10 09:21 UTC, merged