Add a test to check element resolving
eclipse-esmf/esmf-sdk-py-aspect-model-loader pull request #28
Opened 2024-02-13 10:16 UTC by Hanna-Shalamitskaya-EPAM

Changes:

- Added a test for the element resolving logic

2024-02-13 10:17 UTC, Yauhenikapl approved these changes

2024-02-13 12:12 UTC, atextor requested changes

2024-02-13 12:12 UTC, atextor commented on core/esmf-aspect-meta-model-python/tests/integration/resources/com.bosch.test.models/0.2.0/AspectWithProperties.ttl
> +:ProcessParameters a samm:Aspect ;
Please use a neutral Aspect Model name

2024-02-13 12:12 UTC, atextor commented on core/esmf-aspect-meta-model-python/tests/integration/resources/com.bosch.test.models/0.2.0/AspectWithProperties.ttl
> +@prefix : <urn:samm:com.bosch.test.models:0.2.0#>.
The test namespace should be `urn:samm:org.eclipse.esmf.test:1.0.0#`

2024-02-13 12:12 UTC, atextor commented on core/esmf-aspect-meta-model-python/tests/integration/resources/com.bosch.test.models/0.2.0/AspectWithProperties.ttl
> +@prefix type: <urn:samm:com.bosch.test.type:0.2.0#> .
If this needs to be in another namspace than the default test namespace, it should be included in it, e.g. `urn:samm:org.eclipse.esmf.test.other:1.0.0#`

2024-02-13 12:12 UTC, atextor commented on core/esmf-aspect-meta-model-python/tests/integration/resources/com.bosch.test.models/0.2.0/Part_shared.ttl
> +:processedPartId a samm:Property ;
Please use a neutral model element name

2024-02-13 12:12 UTC, atextor commented on core/esmf-aspect-meta-model-python/tests/integration/resources/com.bosch.test.models/0.2.0/Part_shared.ttl
> +    samm:preferredName "Processed Part ID"@en ;
Adapt to neutral element name

2024-02-13 12:12 UTC, atextor commented on core/esmf-aspect-meta-model-python/tests/integration/resources/com.bosch.test.models/0.2.0/Part_shared.ttl
> +    samm:description "The identification of the processed part based on part number."@en ;
Remove

2024-02-13 12:12 UTC, atextor commented on core/esmf-aspect-meta-model-python/tests/integration/resources/com.bosch.test.models/0.2.0/Part_shared.ttl
> +    samm:exampleValue "F03Z1234560213107000283011234567990" ;
Remove

2024-02-13 12:12 UTC, atextor commented on core/esmf-aspect-meta-model-python/tests/integration/resources/com.bosch.test.models/0.2.0/Part_shared.ttl
> +    samm:see <https://inside-docupedia.bosch.com/confluence/x/ssq0O> ;
Remove

2024-02-13 12:12 UTC, atextor commented on core/esmf-aspect-meta-model-python/tests/integration/resources/com.bosch.test.type/0.2.0/Material_shared.ttl
> +:materialNumber a samm:Property ;
Please use neutral model element name

2024-02-13 12:12 UTC, atextor commented on core/esmf-aspect-meta-model-python/tests/integration/resources/com.bosch.test.type/0.2.0/Material_shared.ttl
> +    samm:preferredName "Material Number"@en ;
Remove

2024-02-13 12:12 UTC, atextor commented on core/esmf-aspect-meta-model-python/tests/integration/resources/com.bosch.test.type/0.2.0/Material_shared.ttl
> +    samm:preferredName "Materialnummer"@de ;
Remove

2024-02-13 12:12 UTC, atextor commented on core/esmf-aspect-meta-model-python/tests/integration/resources/com.bosch.test.type/0.2.0/Material_shared.ttl
> +    samm:description "The identification of the product based on the SAP material number."@en ;
Remove

2024-02-13 12:12 UTC, atextor commented on core/esmf-aspect-meta-model-python/tests/integration/resources/com.bosch.test.type/0.2.0/Material_shared.ttl
> +    samm:exampleValue "F03Z12345602" ;
Remove

2024-02-14 14:55 UTC, atextor approved these changes

2024-02-15 10:55 UTC, merged