Added SAMM meta model class for units
eclipse-esmf/esmf-sdk-py-aspect-model-loader pull request #36
Opened 2024-05-23 11:36 UTC by Hanna-Shalamitskaya-EPAM

## Description

Changes:
- Added SAMM meta model module;
- Created SammUnitsGraph class for getting access to the parameter units;
- Added unit tests for the SammUnitsGraph class.

## Type of change

Please delete options that are not relevant.

- [X] New feature (non-breaking change which adds functionality)

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works

2024-05-27 07:18 UTC, Hanna-Shalamitskaya-EPAM commented on core/esmf-aspect-meta-model-python/esmf_aspect_meta_model_python/samm_meta_model.py
> +#  Copyright (c) 2023 Robert Bosch Manufacturing Solutions GmbH
No, should be the current year.
Thanks for for carefully checking

2024-05-27 07:19 UTC, Hanna-Shalamitskaya-EPAM commented on core/esmf-aspect-meta-model-python/esmf_aspect_meta_model_python/samm_meta_model.py
> +#  Copyright (c) 2023 Robert Bosch Manufacturing Solutions GmbH
Fixed

2024-06-04 14:19 UTC, atextor requested changes

2024-06-04 14:19 UTC, atextor commented on core/esmf-aspect-meta-model-python/README.md
> +## SAMM meta model
```suggestion
## Semantic Aspect Meta Model
```

2024-06-04 14:19 UTC, atextor commented on core/esmf-aspect-meta-model-python/README.md
> +To be able to use "SAMM meta model" classes you need to download "SAMM Aspect Meta Model for development" ([Set Up SAMM Aspect Meta Model for development](#Set Up SAMM Aspect Meta Model for developme
```suggestion
To be able to use SAMM meta model classes you need to download the corresponding files. Details are described in [Set up SAMM Aspect Meta Model for development](#set-up-samm-aspect-meta-model-for-development).
```

2024-06-04 14:19 UTC, atextor commented on core/esmf-aspect-meta-model-python/README.md
> +This module contains classes for working with SAMM data.
```suggestion
This module contains classes for working with Aspect data.
```

2024-06-05 05:02 UTC, atextor approved these changes

2024-06-05 05:02 UTC, merged