#43 state initiator implementation
eclipse-esmf/esmf-sdk-py-aspect-model-loader pull request #45
Opened 2024-08-12 10:05 UTC by thec0dewriter

## Description

added a first implementation mainly based on the Enum implementation, given it's an enum with a default value.
Maybe a better option would be to reuse the enum implementation

Fixes #43 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works

## Additional notes:

Add any other notes or comments here.

2024-08-12 10:06 UTC, thec0dewriter commented
Hi @atextor,
Fixed the Eclipse Contributor check

2024-08-20 04:59 UTC, atextor requested changes
The PR looks good to me, although one minor change is necessary to make the code style checker happy.

2024-08-20 04:59 UTC, atextor commented on core/esmf-aspect-meta-model-python/tests/integration/test_characteristics.py
> +    State
Apparently the code style check fails, because this needs to be sorted lexicographically:
```suggestion
    State,
    StructuredValue
```

2024-09-09 09:39 UTC, Hanna-Shalamitskaya-EPAM commented on core/esmf-aspect-meta-model-python/esmf_aspect_meta_model_python/loader/instantiator/state_instantiator.py
> +        This method instantiates one possible value of an state.
`This method instantiates one possible value of **a** state.`

2024-09-09 09:39 UTC, Hanna-Shalamitskaya-EPAM commented on core/esmf-aspect-meta-model-python/esmf_aspect_meta_model_python/loader/instantiator/state_instantiator.py
> +import typing
For the code consistency, please import only used classes from the **typing** library

`
from typing import Any, Dict, List, Optional
`

2024-09-09 09:39 UTC, Hanna-Shalamitskaya-EPAM commented on core/esmf-aspect-meta-model-python/esmf_aspect_meta_model_python/loader/instantiator/state_instantiator.py
> +    def __to_state_node_value(self, value_node: Node) -> typing.Dict:
value_node can be None
so, definition can update with 
`def __to_state_node_value(self, value_node: Optional[Node])`

in the method **_create_instance**
'
        defaultValue = self._aspect_graph.value(
            subject=element_node,
            predicate=self._sammc.get_urn(SAMMC.default_value),
        )
        default = self.__to_state_node_value(defaultValue)
'
self._aspect_graph.value can return None for the defaultValue

2024-09-09 09:45 UTC, Hanna-Shalamitskaya-EPAM requested changes
Please, correct the parts of the code for which comments have been added.

2024-09-23 07:35 UTC, Hanna-Shalamitskaya-EPAM commented
@thec0dewriter please have a look at comments to your PR

Looking forward for your changes

2024-10-16 17:41 UTC, thec0dewriter commented
Thanks @Hanna-Shalamitskaya-EPAM for the detailed feedback.
I made the suggested modifications, let me know if I missed something

2024-10-21 11:32 UTC, Hanna-Shalamitskaya-EPAM approved these changes
Looks good

2024-10-21 12:30 UTC, atextor approved these changes

2024-10-21 12:50 UTC, merged

2024-10-21 12:50 UTC, atextor commented
Thank you for your contribution @thec0dewriter!

2024-10-22 05:51 UTC, Hanna-Shalamitskaya-EPAM commented
@thec0dewriter, thank you for your contribution